apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Nguyen-Thanh-Huy-io/k8s-devops-blueprint.git
    targetRevision: main
    path: k8s                         

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce

  syncPolicy:
    automated:
      prune: true                      
      selfHeal: true                   
    syncOptions:
      - CreateNamespace=true          
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true           
    retry:
      limit: 3                         
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
