apiVersion: v1
data:
  MARIADB_DB: ZnVsbC1zdGFjay1lY29tbWVyY2U=
  MARIADB_HOST: MTcyLjE2LjEyOS4xMw==
  MARIADB_NAME: ZWNvbW1lcmNlYXBw
  MARIADB_PASSWORD: U3Ryb25nUGE1NVdvckQ=
  MARIADB_PORT: MzMwNg==
kind: Secret
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yRze7TMBDE32XPcYjz5Ti3VEGCQ0nVIHpEG2fTmiZ2iF0kVPXdkQWCcPkfrZ35zYz8BFz1F9qctgZq+MEhgrs2I9TQk9rIQwQLeRzRI9RPQGOsR6+tceFph2+kvCMfb9rGCr2fKdb2nQ4AEhILxVNWJlywXBaSDRVxhgmWUzGIccoSeEUw40Dzm7gbuhvUkCYiL1OVySzhopBVlaIY8jyvhMBs4lLmlSiRpwFqcKHQQdlloU0RG1DdyYwsLBnQEVPWGFJhCvyWuxXVf57AcX7T5tr+mX9szh+b9vC1PUAN02OemfOo7uyfJfqr+dD1n6EGLtKYlzFPZcyz3flTc3y/D8N13V1PTd9funMb/sFv1lxPWBQXu7V7TXcOAVmWlKGp/7mG9t2K3x8Er18BAAD///PDhV3aAQAA
    objectset.rio.cattle.io/id: e79a5c12-6017-4959-b8e1-a0a6f5b7df30
  creationTimestamp: "2026-06-23T15:36:28Z"
  labels:
    objectset.rio.cattle.io/hash: 207462c39301759882a7b444877a3f1994876a12
  name: ecommerce-backend-database-connection
  namespace: ecommerce
  resourceVersion: "339188"
  uid: 0deeaf41-59e8-4864-a391-2a9d61b94652
type: Opaque
