apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend-deployment
  namespace: ecommerce
  labels:
    app: ecommerce-backend
spec:
  selector:
    matchLabels:
      app: ecommerce-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
      - name: ecommerce-backend
        image: huyhuy0210/ecommerce-backend:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: tcp
          protocol: TCP
        envFrom:
        - secretRef:
            name: ecommerce-backend-database-connection
            optional: false
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1028Mi
        volumeMounts:
        - name: ecommerce-backend-application-properties-config-volume
          mountPath: /run/src/main/resources/application.properties
          subPath: application.properties
      volumes:
      - name: ecommerce-backend-application-properties-config-volume
        configMap:
          name: ecommerce-backend-application-properties-configmap
          defaultMode: 420