apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data
    server: 172.16.129.13
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage